version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ComeInMain
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
  comeintrigger:
    image: comeintrigger
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: production

volumes:
  pg_data:
